# See https://docs.github.com/sponsors/getting-started-with-github-sponsors-for-open-source-contributors
# Add your supported funding links below.
# github: [your-github-username]
# patreon: your-patreon-username
# custom: ["https://your-site.example/support"]
