name: Typo / small fix
description: Report a typo or small correction.
title: "[Typo] "
labels: ["typo"]
body:
  - type: input
    id: location
    attributes:
      label: Location
      placeholder: "file + section heading"
    validations:
      required: true
  - type: textarea
    id: fix
    attributes:
      label: Suggested fix
    validations:
      required: true
